---
- hosts: kubernetes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Creating a repository file for node exporters
    file:
     path: /etc/yum.repos.d/prometheus-exporters.repo
     state: touch


  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Adding repository details in prometeus export repo file.
    blockinfile:
     path: /etc/yum.repos.d/prometheus-exporters.repo
     block: |
      [prometheus-exporters]
      name=Copr repo for prometheus-exporters owned by ibotty
      baseurl=https://download.copr.fedorainfracloud.org/results/ibotty/prometheus-exporters/epel-7-$basearch/
      type=rpm-md
      skip_if_unavailable=True
      gpgcheck=1
      gpgkey=https://download.copr.fedorainfracloud.org/results/ibotty/prometheus-exporters/pubkey.gpg
      repo_gpgcheck=0
      enabled=1
      enabled_metadata=1


  - name: Installing Docker and firewalld
    shell: |
     yum install firewalld -y
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y --setopt=best=0

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('kubernetes-master-nodes' in group_names) else worker_ports }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
